language:
  - cpp

compiler:
  #- gcc
  - clang

dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev

before_install:
  # C++14, even C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++14, even C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo apt-get install libboost-all-dev

before_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  - ./tests/unit_tests/unit_tests
  - ./tests/selscript/selscript_tests
  #- ./tests/regression_tests/regression_tests

