dist: xenial
language: cpp
compiler:
    - clang
# Boost
addons:
    apt:
        packages: libboost-all-dev
        packages:
            - libboost-all-dev
            - libstdc++-7-dev
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libgtest-dev
before_script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ..
script:
    - cmake --build .
    - ./test/unit_tests/unit_tests
