dist: xenial
language: cpp
compiler:
    - clang
# Boost
addons:
    apt:
        packages: libboost-all-dev
before_script:
    - mkdir build
    - cd build
    - cmake ..
script:
    - cmake --build .
    - ./test/unit_tests/unit_tests
