name: Build
on: push

jobs:
    build:
        name: build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Download and Install Dependencies
              run: |
                  wget -O boost_1_72_0.tar.gz https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
                  tar xvfz boost_1_72_0.tar.gz
                  cd boost_1_72_0
                  ./bootstrap --with-libraries=chrono,system,program_options,filesystem
                  ./b2
                  sudo ./b2 install

            - name: Check out repository
              uses: actions/checkout@v2
            - name: Configure and Build
              run: |
                  mkdir -p build
                  cd build
                  cmake ..
                  make
