name: Build
on: push

jobs:
    build:
        name: ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}
        strategy:
            fail-fast: false
            matrix:
                config:
                - {
                    name: "Ubuntu Latest GCC",
                    os: ubuntu-latest,
                    cc: "gcc",
                    cxx: "g++",
                  }
                - {
                    name: "Ubuntu Latest clang",
                    os: ubuntu-latest,
                    cc: "clang",
                    cxx: "clang++",
                  }
                - {
                    name: "macOs Latest clang",
                    os: macos-latest,
                    cc: "clang",
                    cxx: "clang++",
                  }
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Download and Install Dependencies
              shell: cmake -P {0}
              run: |
                  set(third_party_libs "$ENV{GITHUB_WORKSPACE}/third_party/")
                  set(boost_version "1.72.0")
                  string(REPLACE "." "_" boost_file "boost_${boost_version}")
                  set(boost_dir ${boost_file})
                  set(boost_file "${boost_file}.tar.gz")
                  set(boost_url "https://dl.bintray.com/boostorg/release/${boost_version}/source/${boost_file}")
                  set(boost_libraries "chrono,system,program_options,filesystem")
                  set(boost_prefix "${third_party_libs}/boost")

                  message(STATUS "Workspace: $ENV{GITHUB_WORKSPACE}")
                  message(STATUS "Third Party Libs: ${third_party_libs}")
                  message(STATUS "Boost Version ${boost_version}")

                  # Download and install Boost
                  file(DOWNLOAD "${boost_url}" "./${boost_file}")
                  execute_process(COMMAND ${CMAKE_COMMAND}
                                          -E tar xvfz "${boost_file}"
                                  OUTPUT_QUIET)
                  execute_process(COMMAND ./bootstrap.sh
                                          --prefix=${boost_prefix}
                                          --with-libraries=${boost_libraries}
                                  WORKING_DIRECTORY "${boost_dir}"
                                  OUTPUT_QUIET)
                  execute_process(COMMAND ./b2
                                  WORKING_DIRECTORY "${boost_dir}"
                                  OUTPUT_QUIET)
                  execute_process(COMMAND ./b2 install
                                  WORKING_DIRECTORY "${boost_dir}")

            - name: Configure and Build
              run: |
                  set CC=${{ matrix.config.cc }}
                  set CXX={{ matrix.config.cxx }}
                  git submodule update --init --recursive
                  mkdir -p ${{ github.workspace }}/build
                  cd ${{ github.workspace }}/build
                  BOOST_ROOT=${GITHUB_WORKSPACE}/third_party/boost cmake .. \
                                                                   -DCMAKE_BUILD_TYPE=Release \
                                                                   -DPAGODA_VERSION=${{ github.repository }}-${{ github.run_number }} \
                                                                   -DPAGODA_BUILD_NUMBER=${{ github.run_number }}
                  cmake --build .

            - name: Run tests
              run: |
                  cd build
                  ./tests/unit_tests/unit_tests
                  ./tests/pgscript/pgscript_tests
                  ./tests/regression_tests/regression_tests
            - name: Pack Regression Test Results
              if: always()
              shell: cmake -P {0}
              run: |
                  execute_process(COMMAND ${CMAKE_COMMAND}
                                          -E tar cJfv "${{ matrix.config.name }}-regression_results.tar.xz" "build/regression_results")
            - name: Upload Regression Test Results
              if: always()
              uses: actions/upload-artifact@v1
              with:
                  path: ./${{ matrix.config.name }}-regression_results.tar.xz
                  name: ${{ matrix.config.name }}-regression_results.tar.xz

            - name: Install
              run: |
                  mkdir -p ${{ github.workspace }}/install_dir
                  cmake --install ${{ github.workspace }}/build --prefix ${{ github.workspace }}/install_dir
            - name: Pack
              shell: cmake -P {0}
              run: |
                  execute_process(COMMAND ${CMAKE_COMMAND}
                                          -E tar cJfv "${{ matrix.config.name }}.tar.xz" "${{ github.workspace }}/install_dir")
            - name: Upload
              uses: actions/upload-artifact@v1
              with:
                  path: ./${{ matrix.config.name }}.tar.xz
                  name: ${{ matrix.config.name }}.tar.xz

    release:
        if: contains(github.ref, 'tags/v')
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1.0.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: false
                prerelease: false

            - name: Store Release url
              run: |
                echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

            - uses: actions/upload-artifact@v1
              with:
                path: ./upload_url
                name: upload_url

    publish:
        if: contains(github.ref, 'tags/v')
        name: ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}
        needs: release
        strategy:
            fail-fast: false
            matrix:
                config:
                - {
                    name: "Ubuntu Latest GCC",
                    os: ubuntu-latest,
                  }
                - {
                    name: "Ubuntu Latest clang",
                    os: ubuntu-latest,
                  }
                - {
                    name: "macOs Latest clang",
                    os: ubuntu-latest,
                  }

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v1
              with:
                  name: ${{ matrix.config.name }}.tar.xz
                  path: ./

            - name: Download URL
              uses: actions/download-artifact@v1
              with:
                name: upload_url
                path: ./
            - id: set_upload_url
              run: |
                upload_url=`cat ./upload_url`
                echo ::set-output name=upload_url::$upload_url

            - name: Upload to Release
              id: upload_to_release
              uses: actions/upload-release-asset@v1.0.1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
                asset_path: ./${{ matrix.config.name }}.tar.xz
                asset_name: ${{ matrix.config.name }}.tar.xz
                asset_content_type: application/x-gtar
