name: Build
on: push

jobs:
    build:
        name: ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}
        strategy:
            fail-fast: false
            matrix:
                config:
                - {
                    name: "Linux",
                    os: ubuntu-latest,
                    compiler: "gcc",
                    build_script: "build.sh"
                  }
                - {
                    name: "macOS",
                    os: macos-latest,
                    compiler: "clang",
                    build_script: "build.sh"
                  }
                - {
                    name: "Windows",
                    os: windows-latest,
                    compiler: "msvc",
                    build_script: "build.bat"
                  }
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                path: 'pagoda'

            - name: Build
              run: ${{ github.workspace }}/pagoda/${{ matrix.config.build_script}} ${{ github.workspace }} ${{ matrix.config.OS }} ${{ matrix.config.compiler }}

            - name: Run tests
              run: |
                  cd build
                  ctest -C Release --output-on-failure

            - name: Install
              run: |
                  mkdir -p ${{ github.workspace }}/install_dir
                  cmake --install ${{ github.workspace }}/build --prefix ${{ github.workspace }}/build/pagoda

            - name: Pack
              shell: cmake -P {0}
              run: |
                  execute_process(COMMAND ${CMAKE_COMMAND}
                                          -E tar cJfv "pagoda-${{ github.ref_name }}-${{ matrix.config.name }}.tar.xz" "${{ github.workspace }}/build/pagoda")

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  path: ./pagoda-${{ github.ref_name }}-${{ matrix.config.name }}.tar.xz
                  name: pagoda-${{ github.ref_name }}-${{ matrix.config.name }}.tar.xz
