name: Build
on: push

jobs:
    build:
        name: ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}
        strategy:
            fail-fast: false
            matrix:
                config:
                - {
                    name: "Ubuntu-gcc",
                    os: ubuntu-latest,
                    OS: "ubuntu",
                    compiler: "gcc"
                  }
                - {
                    name: "macOs-clang",
                    os: macos-latest,
                    OS: "macos",
                    compiler: "clang"
                  }
                - {
                    name: "Windows-msvc",
                    os: windows-2019,
                    OS: "win",
                    compiler: "msvc"
                  }
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                path: 'pagoda'

            - name: Build
              run: ${{ github.workspace }}/pagoda/build.sh ${{ github.workspace }} ${{ matrix.config.OS }} ${{ matrix.config.compiler }}

            - name: Run tests
              run: |
                  cd build
                  ctest -C Release

            - name: Pack Build Results
              if: always()
              shell: cmake -P {0}
              run: |
                  execute_process(COMMAND ${CMAKE_COMMAND}
                                          -E tar cJfv "build-results-${{ matrix.config.name }}.tar.xz" "./")

            - name: Upload Build Results
              if: always()
              uses: actions/upload-artifact@v1
              with:
                  path: ./build-results-${{ matrix.config.name }}.tar.xz
                  name: build-results-${{ matrix.config.name }}.tar.xz

            - name: Install
              run: |
                  mkdir -p ${{ github.workspace }}/install_dir
                  cmake --install ${{ github.workspace }}/build --prefix ${{ github.workspace }}/build/pagoda

            - name: Pack
              shell: cmake -P {0}
              run: |
                  execute_process(COMMAND ${CMAKE_COMMAND}
                                          -E tar cJfv "${{ matrix.config.name }}.tar.xz" "${{ github.workspace }}/build/pagoda")

            - name: Upload
              uses: actions/upload-artifact@v1
              with:
                  path: ./${{ matrix.config.name }}.tar.xz
                  name: ${{ matrix.config.name }}.tar.xz
