name: Build
on: push

jobs:
    build:
        name: ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}
        strategy:
            fail-fast: false
            matrix:
                config:
                - {
                    name: "Ubuntu-gcc",
                    os: ubuntu-latest,
                    set_path: "export PATH=$PATH:/home/runner/.local/bin",
                    conan_profile: './tools/profiles/ubuntu_gcc_Release_gh.txt',
                    cc: "gcc-9",
                    cxx: "g++-9"
                  }
                - {
                    name: "Ubuntu-clang",
                    os: ubuntu-latest,
                    set_path: "export PATH=$PATH:/home/runner/.local/bin",
                    conan_profile: './tools/profiles/ubuntu_clang_Release_gh.txt',
                    cc: "clang",
                    cxx: "clang++"
                  }
                - {
                    name: "macOs-clang",
                    os: macos-latest,
                    set_path: "",
                    conan_profile: './tools/profiles/macos_clang_Release_gh.txt',
                    cc: "clang",
                    cxx: "clang++"
                  }
                - {
                    name: "Windows-msvc",
                    os: windows-latest,
                    set_path: "",
                    conan_profile: './tools/profiles/win_msvc_Release_gh.txt',
                    cc: "",
                    cxx: ""
                  }
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Download and Install Dependencies
              run: |
                  pip3 install wheel setuptools numpy
                  pip3 install conan
            - name: Download and Install Dependencies (Ubuntu)
              if: ${{ contains(matrix.config.os, 'Ubuntu') }}
              run: |
                  sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev

            - name: Configure and Build
              env:
                CC: ${{ matrix.config.cc }}
                CXX: ${{ matrix.config.cxx }}
              run: |
                  ${{ matrix.config.set_path }}
                  git submodule update --init --recursive
                  conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
                  conan remote add helmesjo https://api.bintray.com/conan/helmesjo/public-conan
                  conan remote add pagoda https://api.bintray.com/conan/diegoarjz/Pagoda
                  conan install -if ${{ github.workspace }}/build -pr ${{ matrix.config.conan_profile }} ${{ github.workspace }} --build=missing
                  cd ${{ github.workspace }}/build
                  conan build ${{ github.workspace }}

            - name: Run tests
              if: ${{ !contains(matrix.config.os, 'Windows') }}
              run: |
                  cd build
                  ctest -C Release

            - name: Create package
              run: |
                  ${{ matrix.config.set_path }}
                  conan package -bf build -if build -pf package .

            - name: Pack Build Results
              if: always()
              shell: cmake -P {0}
              run: |
                  execute_process(COMMAND ${CMAKE_COMMAND}
                                          -E tar cJfv "build-results-${{ matrix.config.name }}.tar.xz" "build/")

            - name: Upload Build Results
              if: always()
              uses: actions/upload-artifact@v1
              with:
                  path: ./build-results-${{ matrix.config.name }}.tar.xz
                  name: build-results-${{ matrix.config.name }}.tar.xz

            - name: Install
              run: |
                  mkdir -p ${{ github.workspace }}/install_dir
                  cmake --install ${{ github.workspace }}/build --prefix ${{ github.workspace }}/install_dir

            - name: Pack
              shell: cmake -P {0}
              run: |
                  execute_process(COMMAND ${CMAKE_COMMAND}
                                          -E tar cJfv "${{ matrix.config.name }}.tar.xz" "${{ github.workspace }}/install_dir")

            - name: Upload
              uses: actions/upload-artifact@v1
              with:
                  path: ./${{ matrix.config.name }}.tar.xz
                  name: ${{ matrix.config.name }}.tar.xz

            - name: Conan Package
              if: github.ref == 'ref/head/development'
              env:
                CC: ${{ matrix.config.cc }}
                CXX: ${{ matrix.config.cxx }}
              run: |
                ${{ matrix.config.set_path }}
                conan remote add pagoda https://api.bintray.com/conan/diegoarjz/Pagoda
                conan user -p ${{ secrets.CONAN_API_KEY }} -r pagoda ${{ secrets.CONAN_USER }}
                conan create . pagoda/development
                conan upload pagoda/*@pagoda/development -r pagoda --all --force --retry 3 --retry-wait 60 --confirm

    release:
        if: contains(github.ref, 'tags/v')
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1.0.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: false
                prerelease: false

            - name: Store Release url
              run: |
                echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

            - uses: actions/upload-artifact@v1
              with:
                path: ./upload_url
                name: upload_url

    publish:
        if: contains(github.ref, 'tags/v')
        runs-on: ${{ matrix.config.os }}
        needs: release
        strategy:
            fail-fast: false
            matrix:
                config:
                - {
                    name: "Ubuntu-gcc",
                    os: ubuntu-latest,
                  }
                - {
                    name: "Ubuntu-clang",
                    os: ubuntu-latest,
                  }
                - {
                    name: "macOs-clang",
                    os: ubuntu-latest,
                  }
                - {
                    name: "Windows-msvc",
                    os: windows-latest,
                  }

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v1
              with:
                  name: ${{ matrix.config.name }}.tar.xz
                  path: ./

            - name: Download URL
              uses: actions/download-artifact@v1
              with:
                name: upload_url
                path: ./
            - id: set_upload_url
              run: |
                upload_url=`cat ./upload_url`
                echo ::set-output name=upload_url::$upload_url

            - name: Upload to Release
              id: upload_to_release
              uses: actions/upload-release-asset@v1.0.1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
                asset_path: ./${{ matrix.config.name }}.tar.xz
                asset_name: ${{ matrix.config.name }}.tar.xz
                asset_content_type: application/x-gtar
