name: Windows
on: push

jobs:
  build:
    name: "Build on Windows"
    runs-on: windows-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download and Install Dependencies
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - name: Configure and Build
        run: |
          set PATH="C:/Users/runneradmin/.conan/data/mingw_installer/1.0/conan/stable/package/4145762eb81b9dc84cc7dedbcee89e92fc147dbc/bin/;%PATH%"

          echo "------------------------------------------"
          cd
          dir
          echo %PATH%
          echo "------------------------------------------"

          git submodule update --init --recursive
          conan install -if ${{ github.workspace }}/build -pr ./tools/profiles/win_msys2_Release_gh.txt ${{ github.workspace }} --build=missing
          cd ${{ github.workspace }}/build
          conan build ${{ github.workspace }}
