name: Windows
on: push

jobs:
  build:
    name: "Build on Windows"
    runs-on: windows-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download and Install Dependencies
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - name: Configure and Build
        env:
          CC: "clang"
          CXX: "clang++"
        run: |
          set PATH="C:\msys64\mingw64\bin;%PATH%"

          echo "------------------------------------------"
          dir
          set %PATH%
          echo %PATH%
          echo "------------------------------------------"

          git submodule update --init --recursive
          conan install -if ${{ github.workspace }}/build ${{ github.workspace }} --build=missing
          cd ${{ github.workspace }}/build
          conan build ${{ github.workspace }}
