name: Windows
on: push

jobs:
  build:
    name: "Build on Windows"
    runs-on: windows-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download and Install Dependencies
        run: |
          pip3 install wheel setuptools
          pip3 install conan
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH

      - name: Configure and Build
        env:
          CC: C:\msys64\mingw64\bin\clang.exe
          CXX: C:\msys64\mingw64\bin\clang++.exe
        run: |
          echo "------------------------------------------"
          dir
          dir C:\msys64\mingw64\bin
          $env:path -split ";"
          C:\msys64\mingw64\bin\clang.exe --version
          C:\msys64\mingw64\bin\clang++.exe --version
          echo "------------------------------------------"

          git submodule update --init --recursive
          conan install -if ${{ github.workspace }}/build ${{ github.workspace }} -pr ./tools/profiles/win_clang_Release_gh.txt --build=missing
          cd ${{ github.workspace }}/build
          conan build ${{ github.workspace }}
