name: Windows
on: push

jobs:
  build:
    name: "Build on Windows"
    runs-on: windows-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download and Install Dependencies
        shell: bash
        run: |
          pip3 install wheel setuptools
          pip3 install conan
          echo "/c/msys64/mingw64/bin" >> $GITHUB_PATH

      - name: Configure and Build
        shell: bash
        env:
          CC: /c/msys64/mingw64/bin/gcc.exe
          CXX: /c/msys64/mingw64/bin/g++.exe
        run: |
          echo "------------------------------------------"
          dir /c/msys64/mingw64/bin
          echo %PATH%
          /c/msys64/mingw64/bin/gcc.exe --version
          echo "------------------------------------------"

          git submodule update --init --recursive
          conan install -if ${{ github.workspace }}/build ${{ github.workspace }} -pr ./tools/profiles/win_clang_Release_gh.txt --build=missing
          cd ${{ github.workspace }}/build
          conan build ${{ github.workspace }}
