name: Windows
on: push

jobs:
  build:
    name: "Build on Windows"
    runs-on: windows-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download and Install Dependencies
        shell: C:\msys64 {}
        run: |
          pip3 install wheel setuptools
          pip3 install conan
          echo "/c/msys64/mingw64/bin" >> $GITHUB_PATH

      - name: Configure and Build
        shell: C:\msys64 {}
        env:
          CC: /c/msys64/mingw64/bin/gcc.exe
          CXX: /c/msys64/mingw64/bin/g++.exe
        run: |
          git submodule update --init --recursive
          conan install -if build . -pr ./tools/profiles/win_msys2_Release_gh.txt --build=missing
          cd build
          conan build ..

      - name: Package
        if: always()
        shell: cmake -P {0}
        run: |
            execute_process(COMMAND ${CMAKE_COMMAND} -E tar cJfv "results.tar.xz" ".")

      - name: Upload Regression Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
            path: results.tar.xz
            name: results.tar.xz

