name: Windows
on: push

jobs:
  build:
    name: "Build on Windows"
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Try MSYS2
        shell: msys2 {0}
        run: |
          echo "PATH: ${PATH}"
          which gcc
          which g++
          which cmake
          which make
          which conan
